### ISSUE TITLE
Error: "x" must be numeric

### ISSUE THREAD

**Issue by loukesio** [dunbarlabNIH/barcodetrackR#1]
Hello :) 

I am following the instructions but I am doing a mistake somewhere 
Any help will be highly appreciated 

When I am running the files in the Shiny app it says Error: "x" must be numeric

What is x exactly and how do I make it numeric. 

Hope you see this msg

**Comment by diegoalexespi** [comment]
﻿Hi! Probably has to do with your input data frame. Should have rownames = barcode, colnames = samples, and matrix cells = numeric values

**Comment by loukesio** [comment]
Good point 
I am using though your own data. rhesus1_keyfile and outfile and I am still getting this error.

**Comment by diegoalexespi** [comment]
﻿Ah – I see the error. This is because the “DataStatistics” tab only becomes populated when an optional README is uploaded (not released in my own data). The other tabs should work.

**Comment by loukesio** [comment]
Thank you :)
